### ISSUE TITLE
Browser Console Warning to start shipping own version of jQuery

### ISSUE THREAD

**Issue by SimJoSt** [ChristophWurst/nextcloud_sentry#243]
### Steps to reproduce
1. Run Nextcloud Version 19(.0.3)
2. Run Sentry App Version 7.0.0
3. Open Logging page in Admin Settings

### Expected behaviour
Browser Console should be clear of warnings and errors from Sentry JavaScript.

### Actual behaviour
About 10 warnings per second from `sentry.js`:
```
$ is deprecated: The global jQuery is deprecated. It will be updated to v2.4 in Nextcloud 20 and v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own.
```

**Comment by ChristophWurst** [comment]
Heyo,

thanks for the report.

The logs aren't actually from Sentry. But the Sentry js SDK interjects calls to `console.*`, hence the browser wrongly shows Sentry as emitter of the log line.

If you disable Sentry you will still see the log, but a different origin.

**Comment by SimJoSt** [comment]
Thanks for the information. I have disabled Sentry and it originates in the `globals.js`. I will check again, when we have upgraded to Nextcloud 20 and file a report, it it's still present.
