### ISSUE TITLE
Automatic report functionality

### ISSUE THREAD

**Issue by rugk** [ChristophWurst/nextcloud_sentry#3]
Would not it be useful to automatically report errors to NextCloud? (in an anonymised way, of course, so maybe only report the general issue and not too many details)

So when issues are introduced or so in the wild, NextCloud may notice a special type of error report is common. Other software, like Browsers, also have crash reporters doing something similar, so might help you too.

**Comment by ChristophWurst** [comment]
So with "to Nextcloud" you mean the Organization and not an individual instance, right? We briefly discussed this and right now we probably lack the knowledge and infrastructure for this. But in the long run this could be a great way to improve the software quality and focus on bugs that occur on many instances.

Would be interresting to see what other FOSS use for that.

**Comment by rugk** [comment]
Yeah, I mean you already have a similar feature: The statics report, which can be enabled in the settings.

Other FLOSS software, well… [Firefox' crash reports](https://firefox-source-docs.mozilla.org/toolkit/crashreporter/crashreporter/index.html#) are here. You can also find doc for other (telemetry) stuff there. KInda different though…

**Comment by ChristophWurst** [comment]
I don't think we have any intention on adding such a general reporting service at the moment. Hence, I'm closing this as `wontfix`.

Thank you for your feedback, @rugk!
