### ISSUE TITLE
`ContentSecurityPolicy` is deprecated

### ISSUE THREAD

**Issue by ChristophWurst** [ChristophWurst/nextcloud_sentry#31]
see https://scrutinizer-ci.com/g/ChristophWurst/nextcloud_sentry/inspections/4e8ea455-dfa4-4b75-9e47-5ccb7b27e98a/issues/files/lib/AppInfo/Application.php?status=new&orderField=path&order=asc&honorSelectedPaths=0&issueId=31407887#inspectioncomment-109212580

cc @rullzer

**Comment by rullzer** [comment]
Yes. I'll tackle this properly soon. Because right now it does :boom: as search for example still uses non compatible stuff which is loaded on every page :(

**Comment by ChristophWurst** [comment]
Thanks!
