### ISSUE TITLE
Performance monitoring

### ISSUE THREAD

**Issue by juliushaertl** [ChristophWurst/nextcloud_sentry#329]
### Feature Request

Besides error tracking, Sentry also offers performance monitoring capabilities https://docs.sentry.io/product/performance/

#### Summary

It would probably be interesting to see this can also be used to trace performance metrics of certain operations like db transactions, controller execution or app bootstrap for example. It would also be available for the frontend where it could even gather web vitals metrics.

https://docs.sentry.io/platforms/php/performance/
https://docs.sentry.io/platforms/javascript/performance/
https://docs.sentry.io/product/performance/web-vitals/

We might be able to use or extend the already existing `OCP\Diagnostics\IEventLogger` for that in the server https://github.com/nextcloud/server/blob/215aef3cbdc1963be1bb6bca5218ee0a4b7f1665/lib/public/Diagnostics/IEventLogger.php#L31

**Comment by ChristophWurst** [comment]
With https://github.com/nextcloud/server/pull/36298 we should be able to register a middleware that runs around every request and monitors controller methods as transactions :popcorn:

**Comment by ChristophWurst** [comment]
Tada

![Bildschirmfoto vom 2023-01-24 09-29-59](https://user-images.githubusercontent.com/1374172/214244585-a09de844-d275-4ea2-93e2-eefedacc4126.png)

**Comment by skjnldsv** [comment]
Yesss!!!
Can't wait to see where we lose so much perfs!
