### ISSUE TITLE
This project is on sentry.php@v3.3.1, update to sentry.php@v3.4.0

### ISSUE THREAD

**Issue by skjnldsv** [ChristophWurst/nextcloud_sentry#373]
![image](https://user-images.githubusercontent.com/14975046/159159389-eb3276e6-ed44-49af-b57d-9cd0097c7be5.png)

**Comment by ChristophWurst** [comment]
I think the master lib is up to date, it just lacks a recent release

**Comment by ChristophWurst** [comment]
The lastest release ships 3.12
