### ISSUE TITLE
Please add a descripion for the Nextcloud App Store

### ISSUE THREAD

**Issue by sunjam** [ChristophWurst/nextcloud_sentry#8]
Please add a clear description for this app in the Nextcloud App Store.  All we see in the description is _Sentry client_.  Thank you!
    
![no-description](https://user-images.githubusercontent.com/1787238/33519198-f07aa00a-d756-11e7-99c1-0509fa17e673.png)

**Comment by ChristophWurst** [comment]
Yup, that would be nice. Any sugestions? Feel free to submit a pull request :wink:
